# stale action
- name: "lifecycle/rotten"
  color: "555757"
  aliases: []
  description: Denotes an issue or PR that has aged beyond stale and will be auto-closed.

- name: "lifecycle/stale"
  color: "564908"
  description: Denotes an issue or PR has remained open with no activity and has become stale.
  aliases: ['stale']
