# PR Specific
- name: pr/suggest-squash-merge
  description: PR is in need of a squash merge
  color: '#ffe066'

- name: pr/needs-rebase
  description: PR is in need of a rebase with master
  color: '#fab005'

# kind categorizes
- name: kind/failing-test
  color: '#D93F0B'
  description: Categorizes issue or PR as related to a consistently or frequently failing test

# sizes
- name: size/XS
  color: "#009900"
  description: Denotes a PR that changes 0-9 lines, ignoring generated files.

- name: size/S
  color: "#77bb00"
  description: Denotes a PR that changes 10-29 lines, ignoring generated files.

- name: size/L
  color: "#ee9900"
  description: Denotes a PR that changes 100-499 lines, ignoring generated files.

- name: size/M
  color: "#eebb00"
  description: Denotes a PR that changes 30-99 lines, ignoring generated files.

- name: size/XL
  color: "#ee5500"
  description: Denotes a PR that changes 500-999 lines, ignoring generated files.

- name: size/XXL
  color: "#ee0000"
  description: Denotes a PR that changes 1000+ lines, ignoring generated files.
