schema_version: '0.1'

name: boa
version: '1.0.0'

description:
  short: Boa Example - SnaB - bundle shell script to a powerful modern CLI applications
  long: Boa Example - SnaB - enable you to bundle shell script to a powerful modern CLI applications
  example: boa /foo/bar/example

tasks:
  foo:
    description:
      short: foo script
      long: execute awesome foo script
      example: boa foo [--verbose] PATH
    cmds:
      - ./foo.sh

  bar:
    description:
      short: bar script
    dir: foobar
    flags:
      - name: optionA
        shorthand: o
        usage: My option to handle something
        value: default-bar-value
        type: string
      - name: optionB
        usage: Second option without default value
      - name: optionC
        usage: Boolean option to handle something
        value: false
        type: bool
    cmds:
      - ./bar.sh --optionA="{{ .optionA }}"
      - ./bar.sh --optionA="{{ .optionA }}"{{ if .optionB }} --optionB="{{ .optionB }}"{{ end }}
      - ./bar.sh --optionA="{{ .optionA }}"{{ if .optionC }} --isOptionC{{ end }}
