version: '0.1'

name: snab

description:
  short: 'SnaB - bundle shell script to a powerful modern CLI applications'
  long: 'SnaB - enable you to bundle shell script to a powerful modern CLI applications'
  example: snab /foo/bar/example

tasks:
  foo:
    description:
      short: 'foo script'
      long: 'execute awesome foo script'
      example: 'foo --verbose'
    cmds:
      - ./foo.sh
    dir: 'examples'
    # Args:    cobra.NoArgs,

  bar:
    description:
      short: 'bar script'
    dir: 'examples/foobar'
    cmds:
      - ./bar.sh
