schema_version: 1

name: boa
version: '1.0.0'

description:
  short: 'Boa Example - SnaB - bundle shell script to a powerful modern CLI applications'
  long: 'Boa Example - SnaB - enable you to bundle shell script to a powerful modern CLI applications'
  example: boa /foo/bar/example

tasks:
  foo:
    description:
      short: 'foo script'
      long: 'execute awesome foo script'
      example: 'foo --verbose'
    cmds:
      - ./foo.sh
    dir: 'examples'
    # Args:    cobra.NoArgs,

  bar:
    description:
      short: 'bar script'
    dir: 'examples/foobar'
    flags:
      - name: myoption
        shorthand: o
        usage: My option to handle something
        value: default-bar-value
    cmds:
      - sh bar.sh --option="{{ .myoption }}"
