name: Go CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "5 1 * * *"

jobs:
  testing:
    name: Test- and linting
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Run go fmt
        if: runner.os != 'Windows'
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: Run go vet
        run: go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.2"

      # Run unit tests here, if you start implementing some.

  compile:
    name: Compile application
    runs-on: ubuntu-22.04
    needs: [testing]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...
