name: pr-size-labeler

on: pull_request

jobs:
  size-label:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: size-label
        uses: pascalgn/size-label-action@v0.5.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "XS",
              "10": "S",
              "30": "M",
              "100": "L",
              "500": "XL",
              "1000": "XXL"
            }
