name: sync-labels

on:
  push:
    branches:
      - main
    paths:
      - .github/config/labels_pr.yml
      - .github/config/labels_stale.yml
      - .github/config/labels.yml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Label Sync
        uses: EndBug/label-sync@v2
        with:
          config-file: |
            .github/config/labels_pr.yml
            .github/config/labels_stale.yml
            .github/config/labels.yml
          delete-other-labels: true
